// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-o3ZBf_HIQmQSZMcDUmQBPHQXxiST3RQ',
    appId: '1:758503489032:web:fe8661b73db149e96a9bbd',
    messagingSenderId: '758503489032',
    projectId: 'coopseva-761a1',
    authDomain: 'coopseva-761a1.firebaseapp.com',
    storageBucket: 'coopseva-761a1.firebasestorage.app',
    measurementId: 'G-KCNYVEP31G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNV3mtBFP1s9yrZKeQgV6BjpqFL-_LeQY',
    appId: '1:758503489032:android:607a8be669d89c716a9bbd',
    messagingSenderId: '758503489032',
    projectId: 'coopseva-761a1',
    storageBucket: 'coopseva-761a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNCrBiLdsubb2D9aVUgiKh-9Mzj7HMC2g',
    appId: '1:758503489032:ios:9cbbd407ab7068eb6a9bbd',
    messagingSenderId: '758503489032',
    projectId: 'coopseva-761a1',
    storageBucket: 'coopseva-761a1.firebasestorage.app',
    iosBundleId: 'com.example.formApp2732026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNCrBiLdsubb2D9aVUgiKh-9Mzj7HMC2g',
    appId: '1:758503489032:ios:9cbbd407ab7068eb6a9bbd',
    messagingSenderId: '758503489032',
    projectId: 'coopseva-761a1',
    storageBucket: 'coopseva-761a1.firebasestorage.app',
    iosBundleId: 'com.example.formApp2732026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-o3ZBf_HIQmQSZMcDUmQBPHQXxiST3RQ',
    appId: '1:758503489032:web:801d01af4273e2d46a9bbd',
    messagingSenderId: '758503489032',
    projectId: 'coopseva-761a1',
    authDomain: 'coopseva-761a1.firebaseapp.com',
    storageBucket: 'coopseva-761a1.firebasestorage.app',
    measurementId: 'G-91ERBTRT3J',
  );
}
